### ISSUE TITLE
Document public roadmap

### ISSUE THREAD

**Issue by davidagold** [davidagold/redesmyn#36]
## Checklist

Topics:
- [x] Use of Python subinterpreters to circumvent GIL limitations in Python >=3.12
- [x] Expand input deserialization options
- [x] API to derive AWS constructs from service
- [x] More metrics/collection regimes
- [x] gRPC support
- [x] Construct injection for greater handler flexibility/management endpoints

Housekeeping:
- [x] Link in README
